version: '3.8'
networks:
  grouple-network:
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - grouple-network

  grouple:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:5000"
    networks:
      - grouple-network
    depends_on:
      - postgres