version: '3.8'
networks:
  grouple-dev-network:
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.dev
    networks:
      - grouple-dev-network

  grouple:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "80:5000"
    networks:
      - grouple-dev-network
    depends_on:
      - postgres